services:
  postgres:
    image: postgres:16-alpine
    container_name: testcook01-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: testcook
      POSTGRES_PASSWORD: testcook
      POSTGRES_DB: testcook01
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
